services:
  mssql:
    build: ./init-sql
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - devnet
    restart: unless-stopped

volumes:
  mssql_data:

networks:
  devnet:
    driver: bridge

# ==========================================
# Connection strings for quick reference:
#
# With explicit database (recommended):
#   Server=localhost,1433;
#   Database=main_db;
#   User Id=sa;
#   Password=Password123!;
#   TrustServerCertificate=True;
#
# Without database (connects to master):
#   Server=localhost,1433;
#   User Id=sa;
#   Password=Password123!;
#   TrustServerCertificate=True;
#
# From another container on the 'devnet' network:
#   Server=mssql,1433;
#   Database=main_db;
#   User Id=sa;
#   Password=Password123!;
#   TrustServerCertificate=True;
# ==========================================

