//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms_Template_ASP.NET_.NET_Framework_4._7._2 {
    
    
    public partial class ViewSwitcher {
    }
}
